[package]
name = "powercrust"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rayon = "1.5"
regex = "1.5"
rss = "2.0"
chrono = "0.4"
clap = "3.2"
